# Generated by Django 3.0.3 on 2020-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(max_length=200)),
                ('p_Name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
