# Generated by Django 3.0.3 on 2020-10-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_men_tshirt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='men_tshirt',
            old_name='mts_price',
            new_name='mts_Price',
        ),
    ]
