# Generated by Django 3.0.3 on 2020-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201002_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_tshirt',
            name='mts_Price',
            field=models.CharField(max_length=10),
        ),
    ]
