# Generated by Django 3.0.3 on 2020-10-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_men_jeans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='men_jeans',
            new_name='men_jean',
        ),
    ]
