# Generated by Django 3.0.3 on 2020-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201003_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='men_shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msh_Id', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(max_length=200)),
                ('msh_Name', models.CharField(max_length=50)),
                ('msh_Price', models.CharField(max_length=10)),
            ],
        ),
    ]
