# Generated by Django 3.0.3 on 2020-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_men_shorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='women_tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt_Id', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(max_length=200)),
                ('wt_Name', models.CharField(max_length=50)),
                ('wt_Price', models.CharField(max_length=10)),
            ],
        ),
    ]
